name: calmly
description: A Flutter-based UI design for a peaceful and focused meditation experience.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true


  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.otf
        - asset: assets/fonts/HelveticaNeueMedium.otf
          weight: 600
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeueThin.otf
          weight: 300
