name: calmly
description: A Flutter-based UI design for a peaceful and focused meditation experience.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.7.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/login/
    - assets/images/onboarding/
    - assets/images/topic/
    - assets/images/welcome/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.otf
        - asset: assets/fonts/HelveticaNeueMedium.otf
          weight: 600
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeueThin.otf
          weight: 300
